# GitHub Actions 自动打包配置文件
# 使用方法：
# 1. 在GitHub仓库中创建 .github/workflows/ 目录
# 2. 将此文件改名为 build.yml 并放入该目录
# 3. 提交代码后会自动触发打包

name: 打包Python程序为exe

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: 打包程序
      run: |
        pyinstaller --onefile --noconsole --name=爱心提示 iii.py
    
    - name: 上传打包结果
      uses: actions/upload-artifact@v3
      with:
        name: 爱心提示-exe
        path: dist/爱心提示.exe

