name: 打包Python程序为exe

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

        
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: 打包程序
      run: |
        pyinstaller --onefile --noconsole --name=爱心提示 iii.py
    
    - name: 上传打包结果
      uses: actions/upload-artifact@v4
      with:
        name: 爱心提示-exe
        path: dist/爱心提示.exe
